services:
  backend:
    build:
      context: backend
      target: develop
    # allow the developer to examine the api
    ports:
      - "5000:5000"
    environment:
      MIDATA_TOKEN: ${MIDATA_TOKEN}
      SCOUT_URL: ${SCOUT_URL}
    develop:
      watch:
        - action: sync
          path: backend/
          target: /app
  frontend:
    build:
      context: frontend
      target: dev
      args:
        - VITE_BACKEND_URL=${BACKEND_URL:-http://backend:5000}
    ports:
      - "5173:5173"
    links:
      - backend
    develop:
      watch:
        - action: sync
          path: frontend/
          target: /usr/src/app
