services:
  backend:
    build:
      context: backend
      target: develop
    # allow the developer to examine the api
    ports:
      - "5000:5000"
    environment:
      MIDATA_TOKEN: ${MIDATA_TOKEN}
      SCOUT_URL: ${SCOUT_URL}
      S3_URL: ${S3_ENDPOINT:-http://objectstorage:9000} # Needs to use the internal network service name
      S3_ACCESS_KEY: ${S3_ROOT_USER:-minioadmin}
      S3_SECRET_KEY: ${S3_ROOT_PASSWORD:-minioadmin}
      S3_BUCKET: flask-bucket
    depends_on:
      - objectstorage
    develop:
      watch:
        - action: sync
          path: backend/
          target: /app
    stdin_open: true
    tty: true
  frontend:
    build:
      context: frontend
      target: dev
      args:
        - VITE_BACKEND_URL=${BACKEND_URL:-http://backend:5000}
    ports:
      - "5173:5173"
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: frontend/
          target: /usr/src/app
  objectstorage:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      S3_ROOT_USER: ${S3_ROOT_USER:-minioadmin}
      S3_ROOT_PASSWORD: ${S3_ROOT_PASSWORD:-minioadmin}
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

volumes:
  minio-data:
