services:
  backend:
    build:
      context: backend
      target: prod
  frontend:
    build:
      context: frontend
      target: test
      args:
        - VITE_BACKEND_URL=http://backend:5000
    ports:
      - "4173:4173"
    links:
      - backend
