services:
  backend:
    build:
      context: backend
      target: develop
    # allow the developer to examine the api
    ports:
      - "3000:3000"
    environment:
      MIDATA_TOKEN: ${MIDATA_TOKEN}
      SCOUT_URL: ${SCOUT_URL}
      SWIFT_AUTH_URL: ${SWIFT_AUTH_URL:-http://swift:5000/v3} # Needs to use the internal network service name
      SWIFT_USERNAME: ${SWIFT_USERNAME:-swift}
      SWIFT_PASSWORD: ${SWIFT_PASSWORD:-veryfast}
      SWIFT_PROJECT: ${SWIFT_PROJECT:-service}
      SWIFT_CONTAINER: ${SWIFT_CONTAINER:-example-container}
      SWIFT_REGION: ${SWIFT_REGION:-RegionOne}
    depends_on:
      swift:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: backend/
          target: /app
    stdin_open: true
    tty: true
  frontend:
    build:
      context: frontend
      target: dev
      args:
        - VITE_BACKEND_URL=${BACKEND_URL:-http://backend:3000}
    ports:
      - "5173:5173"
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: frontend/
          target: /usr/src/app
  swift:
    build: ../docker-keystone-swift
    ports:
      - "5000:5000"
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://swift:5000"]
      interval: 10s
      timeout: 2s
