services:
  backend:
    build:
      context: backend
      target: prod
      environment:
        MIDATA_TOKEN: ${MIDATA_TOKEN}
        SCOUT_URL: ${SCOUT_URL}
  frontend:
    build:
      context: frontend
      target: test
      args:
        - VITE_BACKEND_URL=${BACKEND_URL:-http://backend:5000}
    ports:
      - "4173:4173"
    links:
      - backend
