services:
  backend:
    build:
      context: backend
      target: prod
  frontend:
    build:
      context: frontend
      target: prod
      args:
        #- VITE_BACKEND_URL=${VITE_BACKEND_URL}
        - VITE_BACKEND_URL=http://backend:5000
    ports:
      - "8080:80"
    links:
      - backend
