apiVersion: v1
kind: Service
metadata:
  name: who-is-who
spec:
  selector:
    app: who-is-who
    tier: frontend
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: who-is-who
spec:
  selector:
    matchLabels:
      app: who-is-who
      tier: frontend
  template:
    metadata:
      labels:
        app: who-is-who
        tier: frontend
        track: stable
    spec:
      containers:
        - name: who-is-who-frontend-app
          image: ghcr.io/scout-ch/who-is-who-frontend:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: auth-volume
              mountPath: /etc/nginx/auth
              readOnly: true
      volumes:
        - name: auth-volume
          secret:
            secretName: basic-auth
