name: Build and Push

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  FRONTEND_IMAGE_NAME: ${{ github.repository }}-frontend
  BACKEND_IMAGE_NAME: ${{ github.repository }}-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build frontend
      run: |
        docker build --target prod -t ${{ REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:latest frontend/
      
    - name: Push frontend
      run: |
        docker push ${{ REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:latest

    - name: Build backend
      run: |
        docker build --target prod -t ${{ REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:latest backend/
      
    - name: Push backend
      run: |
        docker push ${{ REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:latest
