name: Build and Push

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  FRONTEND_IMAGE_NAME: ${{ github.repository }}-frontend
  BACKEND_IMAGE_NAME: ${{ github.repository }}-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push frontend
      uses: docker/build-push-action@v6
      with:
        context: "{{ defaultContext }}:frontend"
        push: true
        tags: ${{ env.FRONTEND_IMAGE_NAME }}:latest
        target: prod
      
    - name: Build and push backend
      uses: docker/build-push-action@v6
      with:
        context: "{{ defaultContext }}:backend"
        push: true
        tags: ${{ env.BACKEND_IMAGE_NAME }}:latest
        target: prod
